/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsSilicoRouteImport } from './routes/projects.silico'
import { Route as ProjectsMotopulseRouteImport } from './routes/projects.motopulse'
import { Route as ProjectsLumbarRouteImport } from './routes/projects.lumbar'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSilicoRoute = ProjectsSilicoRouteImport.update({
  id: '/silico',
  path: '/silico',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsMotopulseRoute = ProjectsMotopulseRouteImport.update({
  id: '/motopulse',
  path: '/motopulse',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsLumbarRoute = ProjectsLumbarRouteImport.update({
  id: '/lumbar',
  path: '/lumbar',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/projects/lumbar': typeof ProjectsLumbarRoute
  '/projects/motopulse': typeof ProjectsMotopulseRoute
  '/projects/silico': typeof ProjectsSilicoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/projects/lumbar': typeof ProjectsLumbarRoute
  '/projects/motopulse': typeof ProjectsMotopulseRoute
  '/projects/silico': typeof ProjectsSilicoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/projects/lumbar': typeof ProjectsLumbarRoute
  '/projects/motopulse': typeof ProjectsMotopulseRoute
  '/projects/silico': typeof ProjectsSilicoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/projects'
    | '/skills'
    | '/projects/lumbar'
    | '/projects/motopulse'
    | '/projects/silico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/projects'
    | '/skills'
    | '/projects/lumbar'
    | '/projects/motopulse'
    | '/projects/silico'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/projects'
    | '/skills'
    | '/projects/lumbar'
    | '/projects/motopulse'
    | '/projects/silico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SkillsRoute: typeof SkillsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/silico': {
      id: '/projects/silico'
      path: '/silico'
      fullPath: '/projects/silico'
      preLoaderRoute: typeof ProjectsSilicoRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/motopulse': {
      id: '/projects/motopulse'
      path: '/motopulse'
      fullPath: '/projects/motopulse'
      preLoaderRoute: typeof ProjectsMotopulseRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/lumbar': {
      id: '/projects/lumbar'
      path: '/lumbar'
      fullPath: '/projects/lumbar'
      preLoaderRoute: typeof ProjectsLumbarRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsLumbarRoute: typeof ProjectsLumbarRoute
  ProjectsMotopulseRoute: typeof ProjectsMotopulseRoute
  ProjectsSilicoRoute: typeof ProjectsSilicoRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsLumbarRoute: ProjectsLumbarRoute,
  ProjectsMotopulseRoute: ProjectsMotopulseRoute,
  ProjectsSilicoRoute: ProjectsSilicoRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SkillsRoute: SkillsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
